import { useState } from 'react';
import { ArrowUpRight, X } from 'lucide-react';
import { categories, projects, type Project } from '@/data/projects';

export function Work() {
  const [category, setCategory] = useState<string>('All work');
  const [selected, setSelected] = useState<Project | null>(null);
  const visible = category === 'All work' ? projects : projects.filter(project => project.category === category);
  return <section className="work-section" id="work"><div className="section-heading"><span className="section-number">01 / SELECTED WORK</span><div><h2>Made to <em>move</em> you<span className="accent-period">.</span></h2><p>A selection of things imagined, made, and brought to life across disciplines.</p></div></div><div className="filter-bar" aria-label="Filter projects">{categories.map((item, i) => <button key={item} className={category === item ? 'filter active' : 'filter'} onClick={() => setCategory(item)} aria-pressed={category === item}>{item}<sup>{String(i).padStart(2, '0')}</sup></button>)}</div><div className="project-grid">{visible.map((project) => <button className="project-card" key={project.id} onClick={() => setSelected(project)} aria-label={`View ${project.title} project details`}><div className="project-image"><img src={project.image} alt={`${project.title} project visual`} width="768" height="1024" loading="lazy"/><span className="project-open"><ArrowUpRight size={24}/></span></div><div className="project-meta"><span>{String(project.id).padStart(2, '0')} / {project.category.toUpperCase()}</span><span>{project.year}</span></div><div className="project-title-row"><h3>{project.title}</h3><ArrowUpRight size={21} strokeWidth={1.5}/></div><p>{project.type}</p></button>)}</div><p className="work-end">END OF SELECTED WORK <span>—</span> MORE IN THE MAKING</p>{selected && <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelected(null); }} role="presentation"><div className="project-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close project details"><X size={24}/></button><img src={selected.image} alt={`${selected.title} project visual`} width="768" height="1024"/><div className="modal-content"><span className="section-number">{String(selected.id).padStart(2, '0')} / {selected.category.toUpperCase()} / {selected.year}</span><h2 id="modal-title">{selected.title}</h2><p>{selected.description}</p><div className="modal-scope"><span>THE PRACTICE</span><div>{selected.scope.map(item => <span key={item}>{item}</span>)}</div></div><a href={`mailto:hello@motionandmethod.studio?subject=${encodeURIComponent(`A project like ${selected.title}`)}`}>Start something together <ArrowUpRight size={20}/></a></div></div></div>}</section>;
}
